language: php
php:
  - 5.4
before_install:
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install
script:
  - vendor/bin/phpunit
notifications:
  email:
    - "external-ci-notifications+braintree_slim_example@getbraintree.com"
